#!/bin/python3

b = 256
prime = (1 << 61) - 1

def rk(s):
    h = 0
    base = 1
    hashes = [0]*len(s)
    powers = [0]*len(s)
    for i in range(len(s)):
        h = (h + ((base * ord(s[i])) % prime)) % prime
        hashes[i] = h
        powers[i] = base
        base = (base * b) % prime


    for i in range(1, len(s)):
        hash_diff = hashes[i] - hashes[i-1]
        if hash_diff < 0: hash_diff += prime
        inv = pow(powers[i], prime-2, prime)
        print(hash_diff, inv)
        print(i, hash_diff*inv % prime)
    return powers[-1], hashes[-1]


s = 'GGGAACTTCTTCT'
l = 'AGTATATTATAGTAGAGAGGAGAGCGGCGACTACTTATATTTTTTTTTTTCGAGCGAGACGACGGAGGTTTTTTTTTTTCGAGATTCTGCTACGATACGTTTTTTTTTTTCGAGCGCAGATC'
#print(s)
#print(rk(s[3:6]))
#print(rk("ATTCGGATTAGGATTAGG"))
print(rk(l[:23]))
